title: Zork Network Documenation
description: Developer documentation for the Zork Network.

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Zork Network Developers
repo_url: 'https://github.com/ZorkNetwork/docs.zork.network'
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist

#exclude:
#  - assets/
